# Generated by Django 3.1.7 on 2021-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название письма')),
                ('content', models.TextField(blank=True, verbose_name='Содержание письма')),
                ('image', models.ImageField(upload_to='static/main/images', verbose_name='Изображение')),
            ],
        ),
    ]
