# Generated by Django 3.1.7 on 2021-03-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressees',
            name='add',
            field=models.BooleanField(default=False, verbose_name='добавить в рассылку'),
        ),
    ]
